kramdown:
  input: GFM
  toc_levels: 2..3

baseurl: "/parser"
layouts_dir: ".shared/layout"
includes_dir: ".shared/includes"

exclude: ["Gemfile", "Gemfile.lock", "README.md", "vendor"]
safe: true

repository: amphp/parser
gems:
 - "jekyll-github-metadata"
 - "jekyll-relative-links"

defaults:
 - scope:
     path: ""
     type: "pages"
   values:
     layout: "docs"
     description: "PHP's generators are a great way for building incremental parsers. amphp/parser allows parsers to await certain tokens or lengths."
     keywords: ["parser", "streaming parser", "async", "generators", "php", "amphp"]

shared_asset_path: "/parser/asset"
